version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
      - run: npm run lint
      - run: npm run test:unit

workflows:
  test_weather_app:
    jobs:
      - test